### ISSUE TITLE
Unable to run todo app example (Connection refused)

### ISSUE THREAD

**Issue by capt-pyro** [pragmalang/pragma#107]
Running on Ubuntu 20.04, pragmalang v0.3.0

Created a new project and replicated the basic-todo-app example.

Ran the pragma dev command but it threw this error.

Failed to reach or start a local Pragma instance for development. Failed to reach Pragma daemon at http://localhost:9584. Please make sure the daemon is running and retry Connection refused (Connection refused).

Additionally, if it is a port blocking issue is there a way to configure the port?

**Comment by Tabzz98** [comment]
Thank you very much for reporting the issue! I fixed it with [release 0.3.1](https://github.com/pragmalang/pragma/releases/tag/0.3.1). 

Please, consider joining our Discord server (link in the README) and have a chat with us. We'd love to hear your thoughts.

Happy hacking!
