### ISSUE TITLE
Selections not working in `createMany` operations

### ISSUE THREAD

**Issue by anasbarg** [pragmalang/pragma#72]
## The problem

I'm trying to run this query against this [schema](https://gist.github.com/anasbarg/7e9331660f0ae7aa01f7d044631ecb8d)
```gql
mutation  {
  Currency {
    createMany(
      items: [
        { code: "USD", name: { ar: "د.أ", en: "USD" }},
        { code: "JOD", name: { ar: "د.أ", en: "JOD" }}
      ]
    ) {
      code
    }
  }
}
```
and I'm getting this response:
```json
{
  "errors": [
    {
      "message": "key not found: code"
    }
  ]
}
```
### `create` works but not `createMany`
When I use `create` instead of `createMany` it works:
```gql
mutation  {
  Currency {
    create(
      currency:
        { code: "USD", name: { ar: "د.أ", en: "USD" }}
    ) {
      code
    }
  }
}
```
and it returns this response (which is correct):
```json
{
  "data": {
    "Currency": {
      "create": {
        "code": "USD"
      }
    }
  }
}
```
### The insert works but the inner reads (selections) are not being fetched apparently
When I checked the PostgreSQL instance using `psql` I performed the following query, and it gave this output:
```
montaj=# select * from "Currency";
 code |                 name                 
------+--------------------------------------
 USD  | 468f8429-bfaa-44de-b642-da818e3d98fc
 JOD  | 92152f7c-0f2c-4109-be5d-f06016be3189
(2 rows)
```
which means that the inserts are successful but the inner reads (selected fields) are not being fetched correctly. This is odd because the implementation of `createManyRecords` in `PostgresQueryEngine` is:
```scala
  override def createManyRecords(
      model: PModel,
      records: Vector[JsObject],
      innerReadOps: Vector[InnerOperation]
  ): Query[Vector[JsObject]] =
    records.traverse(createOneRecord(model, _, innerReadOps))
``` 
I suspect the problem to be in the `RequestHandler` while converting `TransactionResultMap` to `JsObject`, but I'm not sure.

**Comment by Tabzz98** [comment]
I love these detailed issues.
